name: Auto-Approve PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-approve:
    if: >
      github.event.pull_request.user.login == 'KingMordas' &&
      github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      success()
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          review-message: "Auto-approved by KingMordas"
