name: Automerge

on:
  workflow_run:
    workflows: ["Checks on main PR"]
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Info
        run: |
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "User Login: ${{ github.event.pull_requests.user.login }}"
          echo "Base Ref: ${{ github.base.ref }}"

      - name: Automerge
        if: >
          github.event.workflow_run.conclusion == 'success' &&
          github.event.pull_requests.user.login == 'KingMordas' &&
          github.base.ref == 'main'
        run: gh pr merge --merge --auto
